server {
    listen       80;
    server_name  localhost;

    root   /usr/share/nginx/html;
    index  pages/index.html;

    # Serve static files directly
    location / {
        try_files $uri $uri/ /pages/index.html;
    }

    # Cache static assets
    location ~* \.(js|css)$ {
        expires 1h;
        add_header Cache-Control "public";
    }

    # Security headers
    add_header X-Frame-Options "SAMEORIGIN";
    add_header X-Content-Type-Options "nosniff";

    # Gzip compression
    gzip on;
    gzip_types text/css application/javascript text/html;
}
